apps/usuarios/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
 
urlpatterns = [
    path("logout/", LogoutView.as_view(), name="logout"),
    path("", views.dashboard_usuarios, name="dashboard_usuarios"), 
    path("registrar/", views.registrar_usuario.as_view(), name="registrar_usuario"),
    path("tarjeta/<int:persona_id>/", views.tarjeta_registrar_usuario, name="tarjeta_registrar_usuario"),
    path("registrar_csv/", views.registrar_usuarios_csv, name="registrar_usuarios_csv"),
    path("registrar_csv/reporte/", views.reporte_usuarios_csv, name="reporte_usuarios_csv"),
    path("registrar_csv/limpiar/", views.limpiar_reporte_csv, name="limpiar_reporte_usuarios_csv"),
    path("editar/", views.editar_perfil, name="editar_perfil")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.portal.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('elecciones/', include('apps.elecciones.urls')),
]

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User  
from cloudinary.models import CloudinaryField

class Area(models.Model): 
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre
    
    class Meta:
        verbose_name_plural = "Áreas"
        verbose_name = "Área"

class Persona(models.Model):

    GENERO = [
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    ] 

    cedula = models.CharField(max_length=10, unique=True, null=True, blank=True, default=None)
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    genero = models.CharField(max_length=1, choices=GENERO)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    foto = CloudinaryField('foto', default='DEFAULT_PROFILE_PIC_aszqw2', folder='cec/perfiles', transformation=[{'width': 500, 'height': 500, 'crop': 'limit'}])
    area = models.ForeignKey(Area, on_delete=models.PROTECT, null=True, blank=True, related_name='personas')
    usuario = models.OneToOneField(User, on_delete=models.PROTECT, null=True, blank=True, related_name='persona')
    clave_temporal = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
    class Meta:
        verbose_name_plural = "Personas"
        verbose_name = "Persona"

class Permiso(models.Model): 
    nombre = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return f"{self.nombre}"
    
    class Meta:
        verbose_name_plural = "Permisos"
        verbose_name = "Permiso"

class Permiso_Usuario(models.Model):
    permiso = models.ForeignKey(Permiso, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='permisos')

    def __str__(self):
        return f"{self.usuario.username} es {self.permiso}"
    
    class Meta:
        verbose_name_plural = "Permisos por usuarios"
        verbose_name = "Permiso de usuario"


    

apps/usuarios/views.py
import csv
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import FormView
import io
from apps.usuarios.forms import form_login, form_registrar_usuario, form_registrar_usuario_csv, form_nueva_clave, form_editar_perfil
from apps.usuarios.decorators import permiso_required, permiso_required_cbv
from apps.usuarios.utils import crear_usuario
from core.funciones_generales.utils import ahora
from .models import Area, Persona

# LOGIN
class login_view(LoginView):
    template_name = 'login.html'
    authentication_form = form_login
    redirect_authenticated_user = True
    next_page = reverse_lazy('dashboard')

# INGRESAR NUEVA CONTRASEÑA
@login_required
def ingresar_nueva_clave(request):

    form = form_nueva_clave(user=request.user, data=request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()  

            persona = request.user.persona
            persona.clave_temporal = False
            persona.save()
            persona.refresh_from_db()

            update_session_auth_hash(request, request.user)

            messages.success(request, 'Contraseña actualizada correctamente')
            return redirect('dashboard')

    return render(request, 'ingresar_nueva_clave.html', {'form': form})


# DASHBOARD DE USUARIOS
@login_required
@permiso_required('admin', 'secretaria')
def dashboard_usuarios(request):

    return render(request, "dashboard_usuarios.html")

# FORMULARIO DE REGISTRO DE USUARIO
@permiso_required_cbv('admin', 'secretaria')
class registrar_usuario(LoginRequiredMixin, FormView):
    
    form_class = form_registrar_usuario
    template_name = 'form_registrar_usuario.html'

    def form_valid(self, form):

        try:
            with transaction.atomic():
                
                persona = form.save(commit=False)

                user, password_temporal = crear_usuario(persona)

                persona.save()

                self.request.session['password_temporal'] = password_temporal
                self.persona_id = persona.id

        except Exception as e:
            form.add_error(None, 'Ocurrió un error al registrar el usuario.')
            return self.form_invalid(form)

        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('tarjeta_registrar_usuario', kwargs={'persona_id': self.persona_id})
    
# TARJETA DE DATOS DE PERSONA
@login_required
@permiso_required('admin', 'secretaria')
def tarjeta_registrar_usuario(request, persona_id):

    persona = get_object_or_404(Persona, id=persona_id)
    password = request.session.pop('password_temporal', None)

    context = {
        'persona': persona,
        'password_temporal': password
    }

    return render(request, "tarjeta_registrar_usuario.html", context)

# REGISTRO DE USUARIOS CON CSV
@login_required
@permiso_required('admin')
def registrar_usuarios_csv(request):

    if request.method == 'POST':

        form = form_registrar_usuario_csv(request.POST, request.FILES)

        if form.is_valid():

            archivo = form.cleaned_data['archivo']

            data = archivo.read().decode('utf-8-sig')
        
            reader = csv.DictReader(
                io.StringIO(data),
                delimiter=';'
            )

            personas_creadas = []

            for i, fila in enumerate(reader, start=1):

                if not fila.get('cedula'):
                    continue

                fila = {k: v.strip() if v else v for k, v in fila.items()}

                try:
                    with transaction.atomic():

                        area = Area.objects.filter(nombre=fila['area']).first()

                        persona = Persona.objects.create(
                            cedula=fila['cedula'],
                            nombre=fila['nombre'],
                            apellido=fila['apellido'],
                            genero=fila['genero'],
                            fecha_nacimiento=fila['fecha_nacimiento'] or None,
                            area=area,
                        )

                        usuario, password_temporal = crear_usuario(persona)

                        persona.save()
                        
                        print("==============================================")
                        print(persona.nombre + " " + persona.apellido)
                        print(usuario)

                        personas_creadas.append({
                            'cedula': persona.cedula,
                            'nombre': persona.nombre,
                            'apellido': persona.apellido,
                            'genero': persona.genero,
                            'area': area.nombre if area else '',
                            'username': usuario.username,  
                            'password_temporal': password_temporal,  
                        })

                except Exception as e:

                    messages.error(request,f"Error en cédula {fila.get('cedula')}: {str(e)}")

            request.session['reporte_usuarios'] = personas_creadas

            messages.success(request, f"Se cargaron {len(personas_creadas)} usuarios correctamente")

            return redirect('reporte_usuarios_csv')

    else:
        form = form_registrar_usuario_csv()

    return render(request, 'form_registrar_usuario_csv.html', {'form': form})

# REPORTE DE REGISTRO DE PERSONAS CON CSV
@login_required
@permiso_required('admin')
def reporte_usuarios_csv(request):

    registros = request.session.get('reporte_usuarios', [])

    if not registros:
        return redirect('registrar_usuarios_csv')

    context = {
        'registros': registros,
        'ahora': ahora
    }

    return render(request, 'reporte_usuarios_csv.html', context)

# LIMPIAR REPORTE
@login_required
@permiso_required('admin')
def limpiar_reporte_csv(request):

    request.session.pop('reporte_usuarios', None)

    return redirect('dashboard_usuarios')

#EDITAR PERFIL
@login_required
def editar_perfil(request):

    persona = request.user.persona

    if request.method == 'POST':

        form = form_editar_perfil(request.POST, request.FILES, instance=persona)

        if form.is_valid():

            form.save()

            messages.success(request, 'Información actualizada correctamente.')
            return redirect('dashboard')

    else:
        form = form_editar_perfil(instance=persona)

    return render(request, 'form_editar_perfil.html', {'form': form})

apps/usuarios/templates/form_editar_perfil.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="cec-claro" class="scroll-smooth">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Perfil</title>
    {% if debug %}
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
    {% else %}
    <link rel="stylesheet" href="{% static 'css/output.min.css' %}">
    {% endif %}
    <link rel="stylesheet" href="{% static 'css/detalles.css' %}">
    <link rel="icon" href="{% static 'img/LOGO_ICONO.png' %}">
</head>

<body class="bg-base-300 min-h-screen font-montserrat">

    <div class="drawer lg:drawer-open">
        <input id="my-drawer-4" type="checkbox" class="drawer-toggle" />
        <div class="drawer-content">
            <!-- Navbar -->
            <nav class="print:hidden navbar w-full bg-base-200 flex items-center justify-between">
            <label for="my-drawer-4" aria-label="open sidebar" class="btn btn-square btn-ghost">
                <!-- Sidebar toggle icon -->
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="none" stroke="currentColor" class="my-1.5 inline-block size-4"><path d="M4 4m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path><path d="M9 4v16"></path><path d="M14 10l2 2l-2 2"></path></svg>
            </label>

            <div class="flex flex-wrap space-x-3 items-center">

                <div class="text-xs">
                    {{ usuario_nombre }}
                </div>

                <div class="avatar">

                    <div class="w-7 rounded-full mr-2 ring-accent ring-2">
                        <a href="{% url 'editar_perfil' %}"><img src="{{ usuario_foto }}" /></a>
                    </div>

                </div>

            </div>
            
            </nav>
            <!-- Page content here -->

            {% for message in messages %}

                {% if message.tags == 'success' %}
                <div role="alert" class="fixed bottom-5 z-50 alert alert-success transition-opacity duration-1000 left-1/2 transform -translate-x-1/2 lg:left-auto lg:right-5 lg:translate-x-0">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <span>{{ message }}</span>
                </div>
                {% endif %}

                {% if message.tags == 'error' %}
                <div role="alert" class="fixed bottom-5 z-50 alert alert-error transition-opacity duration-1000 left-1/2 transform -translate-x-1/2 lg:left-auto lg:right-5 lg:translate-x-0">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <span>{{ message }}</span>
                </div>
                {% endif %}

            {% endfor %}

            <div class="flex flex-col items-center justify-center">

                <h1 class="font-montserrat text-center font-black text-2xl text-black hidden print:block mt-10">TARJETA DE DATOS</h1>

                <form method="POST" enctype="multipart/form-data" autocomplete="off" novalidate class="relative bg-base-100 rounded-3xl w-80 print:w-150 h-auto border border-accent/50 m-10 p-10 space-y-4 shadow-lg">

                    <div class="avatar flex justify-center items-center">

                        <div class="w-20 rounded-full mr-2 ring-accent ring">
                            <img src="{{ usuario_foto }}" />
                        </div>

                    </div>

                    {% csrf_token %}

                    <h1 class="font-montserrat text-center font-semibold print:hidden">Editar Perfil</h1>

                    <p class="font-montserrat text-sm print:text-2xl print:text-black font-medium">Cédula: <span class="font-light">{{ usuario_persona.cedula }}</span></p>
                    <p class="font-montserrat text-sm print:text-2xl print:text-black font-medium">Nombre: <span class="font-light">{{ usuario_nombre }}</span></p>
                    <p class="font-montserrat text-sm print:text-2xl print:text-black font-medium">Apellido: <span class="font-light">{{ usuario_apellido }}</span></p>
                    <p class="font-montserrat text-sm print:text-2xl print:text-black font-medium">Género: <span class="font-light">{{ usuario_persona.get_genero_display }}</span></p>
                    <!-- <p class="font-montserrat text-sm print:text-2xl print:text-black font-medium">Fecha de nacimiento: <span class="font-light">{{ usuario_persona.fecha_nacimiento|date:"d-m-Y" }}</span></p> -->
                    <p class="font-montserrat text-sm print:text-2xl print:text-black font-medium">Área: <span class="font-light">{{ usuario_persona.area }}</span></p>
                    <p class="font-montserrat text-sm print:text-2xl print:text-black font-medium">Usuario: <span class="font-light">{{ usuario_persona.usuario.username }}</span></p>

                    <label class="font-montserrat text-sm font-light">Fecha de nacimiento</label>
                    <div>
                        <input
                            type="text"
                            name="fecha_nacimiento"
                            value="{% if usuario_persona.fecha_nacimiento %}{{ usuario_persona.fecha_nacimiento|date:'d-m-Y' }}{% endif %}"
                            class="bg-neutral-content rounded-lg text-xs font-montserrat font-medium input form-accent mt-2 border-0 focus:outline-none focus:ring-1 focus:ring-accent/50"
                            placeholder="dd-mm-aaaa"
                        />

                        {% for error in form.fecha_nacimiento.errors %}
                            <p class="font-montserrat mt-1 text-xs text-error animate-pulse">
                                {{ error }}
                            </p>
                        {% endfor %}
                    </div>

                    <label class="font-montserrat text-sm font-light">Foto</label>
                    <div>
                        {{ form.foto }}

                        {% for error in form.foto.errors %}
                            <p class="font-montserrat mt-1 text-xs text-error animate-pulse">
                                {{ error }}
                            </p>
                        {% endfor %}
                    </div>

                    <button type="submit" class="mt-9 print:hidden rounded-lg btn border-0 w-full items-center bg-primary/80 text-primary-content hover:bg-primary/90 active:bg-primary">Guardar</button>

                </form>
            
            </div>

        </div>

        <div class="print:hidden drawer-side is-drawer-close:overflow-visible">
            <label for="my-drawer-4" aria-label="close sidebar" class="drawer-overlay"></label>
                <div class="flex min-h-full flex-col items-start bg-base-100 is-drawer-close:w-14 is-drawer-open:w-64">
                <!-- Sidebar content here -->
                <ul class="menu w-full grow">
                    <!-- List item -->
                    <li>
                    <a href="{% url 'dashboard' %}" class="is-drawer-close:tooltip is-drawer-close:tooltip-right" data-tip="Dashboard">
                        <!-- Home icon -->
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="none" stroke="currentColor" class="my-1.5 inline-block size-4"><path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"></path><path d="M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path></svg>
                        <span class="is-drawer-close:hidden">Dashboard</span>
                    </a>
                    </li>

                    <li>
                    <a href="{% url 'editar_perfil' %}" class="is-drawer-close:tooltip is-drawer-close:tooltip-right" data-tip="Editar perfil">
                        <!-- Settings icon -->
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640" stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="currentColor" stroke="currentColor" class="my-1.5 inline-block size-4"><path d="M505 122.9L517.1 135C526.5 144.4 526.5 159.6 517.1 168.9L488 198.1L441.9 152L471 122.9C480.4 113.5 495.6 113.5 504.9 122.9zM273.8 320.2L408 185.9L454.1 232L319.8 366.2C316.9 369.1 313.3 371.2 309.4 372.3L250.9 389L267.6 330.5C268.7 326.6 270.8 323 273.7 320.1zM437.1 89L239.8 286.2C231.1 294.9 224.8 305.6 221.5 317.3L192.9 417.3C190.5 425.7 192.8 434.7 199 440.9C205.2 447.1 214.2 449.4 222.6 447L322.6 418.4C334.4 415 345.1 408.7 353.7 400.1L551 202.9C579.1 174.8 579.1 129.2 551 101.1L538.9 89C510.8 60.9 465.2 60.9 437.1 89zM152 128C103.4 128 64 167.4 64 216L64 488C64 536.6 103.4 576 152 576L424 576C472.6 576 512 536.6 512 488L512 376C512 362.7 501.3 352 488 352C474.7 352 464 362.7 464 376L464 488C464 510.1 446.1 528 424 528L152 528C129.9 528 112 510.1 112 488L112 216C112 193.9 129.9 176 152 176L264 176C277.3 176 288 165.3 288 152C288 138.7 277.3 128 264 128L152 128z"/></svg>
                        <span class="is-drawer-close:hidden">Editar perfil</span>
                    </a>
                    </li>

                    <!-- List item -->
                    <li>
                    <button class="is-drawer-close:tooltip is-drawer-close:tooltip-right" data-tip="Tema">
                        <!-- Settings icon -->

                        <label class="swap swap-rotate cursor-pointer">

                            <input type="checkbox" id="cambio_tema" />

                            <!-- CLARO -->
                            <svg class="swap-on size-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,                
                                1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,
                                17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,
                                2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,
                                1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,
                                7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,
                                1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,
                                6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,
                                1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,
                                1.41A1,1,0,0,0,17.66,7.34ZM21,
                                11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,
                                8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,
                                1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,
                                18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,
                                0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,
                                12,5.51,5.51,0,0,0,12,6.5Zm0,
                                9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,
                                12,15.5Z" />
                            </svg>

                            <!-- OSCURO -->
                            <svg class="swap-off size-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                <path fill="none" stroke="currentColor" stroke-width="2" d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
                            </svg>

                        </label>

                        <label for="cambio_tema" class="cursor-pointer is-drawer-close:hidden">
                            Tema
                        </label>
                </button>
                </li>

                <li>
                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="is-drawer-close:tooltip is-drawer-close:tooltip-right" data-tip="Salir">
                            <!-- Settings icon -->
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640" stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="none" stroke="currentColor" class="my-1.5 inline-block size-4"><path fill="#ff5739" d="M224 160C241.7 160 256 145.7 256 128C256 110.3 241.7 96 224 96L160 96C107 96 64 139 64 192L64 448C64 501 107 544 160 544L224 544C241.7 544 256 529.7 256 512C256 494.3 241.7 480 224 480L160 480C142.3 480 128 465.7 128 448L128 192C128 174.3 142.3 160 160 160L224 160zM566.6 342.6C579.1 330.1 579.1 309.8 566.6 297.3L438.6 169.3C426.1 156.8 405.8 156.8 393.3 169.3C380.8 181.8 380.8 202.1 393.3 214.6L466.7 288L256 288C238.3 288 224 302.3 224 320C224 337.7 238.3 352 256 352L466.7 352L393.3 425.4C380.8 437.9 380.8 458.2 393.3 470.7C405.8 483.2 426.1 483.2 438.6 470.7L566.6 342.7z"/></svg>
                            <span class="is-drawer-close:hidden text-error">Salir</span>
                        </button>
                    </form>
                </li>

            </ul>
            </div>
        </div>
    </div>

</body>

<script src="{% static 'js/theme.js' %}"></script>
<script src="{% static 'js/alertas.js' %}"></script>

</html>